version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/faisal-990/ProjectInvestApp"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs", "browser"]
