build:
	@echo "Building Process Starting....."
	@go build -o bin/app cmd/main.go
	@echo "Build completed."

run:
	@echo "Run mode starting to compile and run"
	@go run cmd/main.go

clean:
	@echo "Cleaning build artifacts ....."
	@rm -rf ./bin
	@echo "Build artifacts cleaned"

